avatar:
  url: /images/head.jpg # 你的头像图片地址
  rounded: true
  opacity: 1

banner:
  enable: true
  title: 剑歌浸水寒
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line
